CREATE DATABASE IF NOT EXISTS 287_D
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE 287_D;

CREATE TABLE users (
user_id       INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
username      VARCHAR(100) NOT NULL,
email         VARCHAR(255) NOT NULL UNIQUE,
password      VARCHAR(255) NOT NULL,
created_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;


CREATE TABLE rooms (
room_id      INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
name         VARCHAR(50) NOT NULL UNIQUE
) ENGINE=InnoDB;

CREATE TABLE room_bookings (
booking_id   INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
user_id      INT UNSIGNED NOT NULL,
room_id      INT UNSIGNED NOT NULL,
booking_date DATE NOT NULL,
start_time   TIME NOT NULL,
end_time     TIME NOT NULL,
created_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

CONSTRAINT room_bookings_user
FOREIGN KEY (user_id) REFERENCES users(user_id)
ON DELETE CASCADE,

CONSTRAINT room_bookings_room
FOREIGN KEY (room_id) REFERENCES rooms(room_id)
ON DELETE RESTRICT
) ENGINE=InnoDB;

